name: Central Workflow

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  trigger-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger workflows in listed repositories
        id: trigger-workflows
        run: |
          response=$(curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Code-etp/studynow/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}' \
            -w "\nHTTP_STATUS:%{http_code}")

          # Extract the HTTP status code and response body
          http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d':' -f2)
          response_body=$(echo "$response" | sed '/HTTP_STATUS:/d')

          echo "HTTP Status: $http_status"
          echo "Response Body: $response_body"

          # Fail the step if the HTTP status is not 204 (success)
          if [ "$http_status" != "204" ]; then
            echo "Failed to trigger workflow. Exiting."
            exit 1
          fi
