name: Central Workflow
on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  trigger-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read repository list
        id: read-repos
        run: |
          echo "repos=$(cat target-repos.json)" >> $GITHUB_OUTPUT

      - name: Trigger workflows in repositories
        id: trigger-workflows
        run: |
          # Read the JSON file and process each repository
          repos_json=$(cat target-repos.json)
          
          for repo in $(echo "$repos_json" | jq -c '.repositories[]'); do
            repo_name=$(echo $repo | jq -r '.name')
            workflow=$(echo $repo | jq -r '.workflow')
            branch=$(echo $repo | jq -r '.branch')
            
            echo "Triggering workflow for $repo_name"
            
            response=$(curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$repo_name/actions/workflows/$workflow/dispatches" \
              -d "{\"ref\":\"$branch\"}" \
              -w "\nHTTP_STATUS:%{http_code}")
            
            # Extract the HTTP status code and response body
            http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d':' -f2)
            response_body=$(echo "$response" | sed '/HTTP_STATUS:/d')
            
            echo "HTTP Status for $repo_name: $http_status"
            echo "Response Body for $repo_name: $response_body"
            
            # Check if the request was successful
            if [ "$http_status" != "204" ]; then
              echo "Failed to trigger workflow for $repo_name"
              exit 1
            fi
            
            echo "Successfully triggered workflow for $repo_name"
          done