name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'triggering workflow'
        required: false
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="Code-etp" 
          repo_name="ansible-setup"  
          event_type="trigger-workflow" 
          service="default-service" 
          version="v1.0.0" 
          branch="main"

          echo "Triggering workflow in $repo_owner/$repo_name on branch $branch..."

          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}, \"ref\": \"$branch\"}" \
            -s -o /dev/null -w "%{http_code}")

          if [ "$response" -eq 204 ]; then
            echo "Workflow triggered successfully!"
          else
            echo "Failed to trigger workflow. HTTP status code: $response"
            echo "Debugging information:"
            echo "Repo: $repo_owner/$repo_name"
            echo "Branch: $branch"
            echo "Event Type: $event_type"
            echo "Service: $service"
            echo "Version: $version"
            exit 1
          fi