name: Central Workflow
on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  trigger-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger workflows in repositories
        run: |
          # Read each line from the repos file
          while IFS=, read -r repo workflow branch || [ -n "$repo" ]; do
            # Skip empty lines and comments
            [[ -z $repo ]] && continue
            [[ $repo = \#* ]] && continue
            
            echo "::group::Triggering workflow for $repo"
            
            response=$(curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$repo/actions/workflows/$workflow/dispatches" \
              -d "{\"ref\":\"$branch\"}" \
              -w "\nHTTP_STATUS:%{http_code}")
            
            # Extract the HTTP status code
            http_status=$(echo "$response" | grep "HTTP_STATUS:" | cut -d':' -f2)
            
            if [ "$http_status" != "204" ]; then
              echo "::error::Failed to trigger workflow for $repo (Status: $http_status)"
              exit 1
            fi
            
            echo "✓ Successfully triggered workflow for $repo"
            echo "::endgroup::"
            
          done < target-repos.txt